[[alacritty]]
platform = "linux"
source = "alacritty/alacritty-linux.toml"
target = "~/.config/alacritty/alacritty.toml"

[[alacritty]]
platform = "mac"
source = "alacritty/alacritty-mac.toml"
target = "~/.config/alacritty/alacritty.toml"

[[alacritty]]
source = "alacritty/themes/"
target = "~/.config/alacritty/themes/"

[[fish]]
source = "fish/config.fish"
target = "~/.config/fish/config.fish"

[[git]]
source = "git/config"
target = "~/.config/git/config"

[[starship]]
source = "starship/starship.toml"
target = "~/.config/starship.toml"

[[zsh]]
source = "zsh/zshenv"
target = "~/.zshenv"

[[zsh]]
source = "zsh/zprofile"
target = "~/.zprofile"

[[zsh]]
source = "zsh/zshrc"
target = "~/.zshrc"
